@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml


Person(resident, "Жилец (собственник / член семьи)", "Использует мобильное приложение для управления умными устройствами, а так же получение информации от УК")

System(propApp, "Экосистема PropDevelopment", "Мобильное приложение и backend-сервисы для собственников:\nЖКХ, уведомления от УК, управление «Умным домом»")

System_Ext(authService, "Сервис регистрации и аутентификации", "Единый сервис аутентификации пользователей\n(собственники и члены семьи)")

System_Ext(smartPartner, "Партнёрская платформа «Умный дом»", "Интеллектуальный домофон и шлагбаум:\nраспознавание лиц и номеров ТС,\nуправление физическим доступом")

System_Ext(iotDevices, "IoT-устройства", "Домофоны, камеры, шлагбаумы")

System_Ext(ukSystems, "Сервис УК", "Данные о доме, инфраструктуре, оплата ЖКХ, уведомления для жильцов")

Rel(resident, propApp, "Управляет доступом,\nоткрывает домофон и шлагбаум,\nпросматривает события", "HTTPS")

Rel(propApp, authService, "Аутентификация и авторизация", "OAuth / Tokens")

Rel(propApp, smartPartner, "Передача команд управления доступом,\nнастройка разрешений,\nполучение событий", "API / HTTPS")

Rel(smartPartner, iotDevices, "Управление устройствами и обработка событий", "IoT protocols")

Rel(propApp, ukSystems, "Получение данных о доме и инфраструктуре", "API")

@enduml
